version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_CHAT}
      POSTGRES_USER: ${POSTGRES_USER_CHAT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_CHAT}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
